# Generated by Django 3.0.5 on 2020-05-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('profile_image', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profiles')),
                ('searchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Searches')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.CharField(max_length=999)),
                ('datetime', models.DateTimeField()),
                ('profileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Orders')),
                ('profileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='GameReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
                ('reviewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Reviews')),
            ],
        ),
    ]
