# Generated by Django 3.0.5 on 2020-05-07 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200503_1301'),
        ('users', '0002_auto_20200504_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='gameID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
