# Generated by Django 3.0.5 on 2020-05-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_recentlyviewedanonymous'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentlyViewedAnonymous',
        ),
    ]
