# Generated by Django 3.0.5 on 2020-05-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200508_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='recomend',
            new_name='recommend',
        ),
    ]
