# Generated by Django 3.0.5 on 2020-05-12 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_rating'),
        ('users', '0005_remove_recentlyviewed_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gameID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('profileID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.RenameField(
            model_name='recentlyviewedconsoles',
            old_name='productID',
            new_name='consoleID',
        ),
        migrations.DeleteModel(
            name='RecentlyViewed',
        ),
    ]
