# Generated by Django 3.0.5 on 2020-05-08 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20200508_1037'),
        ('users', '0005_auto_20200508_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_information_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.PaymentInformation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shipping_information_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.ShippingInformation'),
        ),
    ]
