# Generated by Django 3.0.5 on 2020-05-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200508_1328'),
        ('users', '0006_auto_20200508_1222'),
    ]

    operations = [
    ]
