# Generated by Django 3.0.5 on 2020-05-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20200504_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carts.Cart'),
        ),
    ]
