# Generated by Django 3.0.5 on 2020-05-08 10:37

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200506_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='card_number',
            field=creditcards.models.CardNumberField(max_length=25),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='cvv',
            field=creditcards.models.SecurityCodeField(max_length=4),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='expiration_date',
            field=creditcards.models.CardExpiryField(),
        ),
    ]
