# Generated by Django 3.0.5 on 2020-05-09 13:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20200508_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Payment_information_id',
            new_name='payment_information_id',
        ),
        migrations.AlterField(
            model_name='shippinginformation',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
