# Generated by Django 3.0.5 on 2020-05-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=999)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='extra_images',
            field=models.ManyToManyField(null=True, to='main.ExtraImages'),
        ),
    ]
