# Generated by Django 3.0.5 on 2020-05-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200503_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraimages',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
