# Generated by Django 3.0.5 on 2020-05-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_extraimages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraimages',
            name='url',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_images',
            field=models.ManyToManyField(to='main.ExtraImages'),
        ),
    ]
