# Generated by Django 3.0.5 on 2020-05-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('connectivity', models.CharField(max_length=999)),
                ('includes', models.CharField(max_length=999)),
                ('storage_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('warranty', models.DateTimeField()),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consoles.Specifications')),
            ],
        ),
    ]
