# Generated by Django 3.0.5 on 2020-05-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
